import json
import re
from pathlib import Path
from urllib.parse import urlparse

import requests
from bs4 import BeautifulSoup


# Define project paths:
# - Project root folder
# - Input path for the generated candidates from Google Places API
# - Output path for the automatically reviewed candidates
PROJECT_ROOT = Path(__file__).resolve().parents[1]
INPUT_PATH = PROJECT_ROOT / "Daten" / "candidates.json"
OUTPUT_PATH = PROJECT_ROOT / "Daten" / "review_candidates.json"


# Positive keywords for DEXA Body Composition.
# These terms indicate that the provider may offer body composition analysis,
# not only bone density measurement.
DEXA_POSITIVE_KEYWORDS = [
    "body composition",
    "körperzusammensetzung",
    "körperfett",
    "körperfettanteil",
    "muskelmasse",
    "lean mass",
    "fat mass",
    "ganzkörperanalyse",
    "body scan",
    "dexa scan",
    "dxa scan",
]


# Keywords that often indicate bone density measurement only.
# These terms are useful, but they are not enough to confirm DEXA Body Composition.
DEXA_BONE_ONLY_KEYWORDS = [
    "knochendichtemessung",
    "osteoporose",
    "knochendichte",
    "bone density",
    "dxa-knochendichtemessung",
    "dexa-knochendichtemessung",
]


# Positive keywords for blood tests as self-payer.
# These terms indicate that a provider may offer blood tests without referral
# or as private/self-payer service.
BLOOD_POSITIVE_KEYWORDS = [
    "selbstzahler",
    "privatleistung",
    "privatleistungen",
    "ohne überweisung",
    "ohne ueberweisung",
    "direktlabor",
    "blutabnahme",
    "laborwerte",
    "blutuntersuchung",
    "bluttest",
    "gesundheitscheck",
    "check-up",
    "vorsorgeuntersuchung",
]


def load_candidates():
    """
    Load provider candidates from Daten/candidates.json.

    Returns:
        list[dict]: List of provider candidates generated by the Google Places API script.
    """
    if not INPUT_PATH.exists():
        raise FileNotFoundError(f"Input file not found: {INPUT_PATH}")

    with open(INPUT_PATH, "r", encoding="utf-8") as file:
        return json.load(file)


def normalize_text(text):
    """
    Normalize website text for keyword matching.

    Args:
        text (str): Raw website text.

    Returns:
        str: Lowercase text with normalized whitespace.
    """
    text = text.lower()
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def fetch_website_text(url):
    """
    Download a website and extract readable text from its HTML.

    Args:
        url (str): Website URL.

    Returns:
        tuple[str, str | None]:
            - extracted normalized website text
            - error message if something failed, otherwise None
    """
    if not url:
        return "", "missing_website"

    parsed_url = urlparse(url)

    if not parsed_url.scheme:
        url = "https://" + url

    try:
        response = requests.get(
            url,
            timeout=15,
            headers={
                "User-Agent": (
                    "Mozilla/5.0 (compatible; AnbieterFinderDACH/1.0; "
                    "+https://example.com)"
                )
            },
        )

        if response.status_code != 200:
            return "", f"http_status_{response.status_code}"

        soup = BeautifulSoup(response.text, "html.parser")

        # Remove script/style/navigation elements because they usually do not contain useful content.
        for tag in soup(["script", "style", "noscript", "svg"]):
            tag.decompose()

        text = soup.get_text(separator=" ")
        return normalize_text(text), None

    except requests.exceptions.RequestException as error:
        return "", str(error)


def find_keywords(text, keywords):
    """
    Search a normalized text for a list of keywords.

    Args:
        text (str): Normalized website text.
        keywords (list[str]): Keywords to search for.

    Returns:
        list[str]: Keywords that were found in the text.
    """
    matched = []

    for keyword in keywords:
        if keyword.lower() in text:
            matched.append(keyword)

    return matched


def build_recommendation(dexa_positive_matches, dexa_bone_only_matches, blood_matches):
    """
    Build a simple recommendation based on keyword matches.

    Returns:
        str: Recommendation for manual review.
    """
    dexa_positive_score = len(dexa_positive_matches)
    dexa_bone_only_score = len(dexa_bone_only_matches)
    blood_score = len(blood_matches)

    if dexa_positive_score >= 2:
        return "possible_dexa_body_composition"

    if blood_score >= 2:
        return "possible_blood_self_payer"

    if dexa_bone_only_score > 0 and dexa_positive_score == 0:
        return "possibly_bone_density_only"

    if dexa_positive_score == 1 or blood_score == 1:
        return "manual_review"

    return "no_relevant_keywords_found"


def review_candidate(candidate):
    """
    Review one provider candidate by downloading its website and matching keywords.

    Args:
        candidate (dict): One candidate from candidates.json.

    Returns:
        dict: Candidate enriched with autoCheck information.
    """
    website = candidate.get("contact", {}).get("website", "")

    website_text, fetch_error = fetch_website_text(website)

    dexa_positive_matches = find_keywords(website_text, DEXA_POSITIVE_KEYWORDS)
    dexa_bone_only_matches = find_keywords(website_text, DEXA_BONE_ONLY_KEYWORDS)
    blood_matches = find_keywords(website_text, BLOOD_POSITIVE_KEYWORDS)

    recommendation = build_recommendation(
        dexa_positive_matches,
        dexa_bone_only_matches,
        blood_matches,
    )

    reviewed_candidate = {
        **candidate,
        "autoCheck": {
            "websiteChecked": bool(website_text),
            "fetchError": fetch_error,
            "dexaBodyCompositionScore": len(dexa_positive_matches),
            "dexaBoneOnlyScore": len(dexa_bone_only_matches),
            "bloodSelfPayerScore": len(blood_matches),
            "matchedKeywords": {
                "dexaBodyComposition": dexa_positive_matches,
                "dexaBoneOnly": dexa_bone_only_matches,
                "bloodSelfPayer": blood_matches,
            },
            "recommendation": recommendation,
            "needsManualReview": True,
        },
    }

    return reviewed_candidate


def main():
    """
    Main execution flow for automatic candidate review.

    Process:
        1. Load candidates from Daten/candidates.json.
        2. Open each provider website if available.
        3. Extract website text.
        4. Search for DEXA and blood-test-related keywords.
        5. Add scores and a recommendation.
        6. Save reviewed candidates to Daten/review_candidates.json.

    Important:
        This script is only a pre-filter.
        The final decision must still be made manually before copying providers
        into src/data/providers.json.
    """
    candidates = load_candidates()
    reviewed_candidates = []

    print(f"{len(candidates)} Kandidaten geladen.")

    for index, candidate in enumerate(candidates, start=1):
        name = candidate.get("name", "Unknown")
        website = candidate.get("contact", {}).get("website", "")

        print(f"[{index}/{len(candidates)}] Prüfe: {name}")

        if not website:
            print("  Keine Website vorhanden.")
        else:
            print(f"  Website: {website}")

        reviewed_candidate = review_candidate(candidate)
        reviewed_candidates.append(reviewed_candidate)

        recommendation = reviewed_candidate["autoCheck"]["recommendation"]
        print(f"  Empfehlung: {recommendation}")

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

    with open(OUTPUT_PATH, "w", encoding="utf-8") as file:
        json.dump(reviewed_candidates, file, indent=2, ensure_ascii=False)

    print()
    print(f"{len(reviewed_candidates)} geprüfte Kandidaten gespeichert in:")
    print(OUTPUT_PATH)


if __name__ == "__main__":
    main()